### ISSUE TITLE
fhempy -> mytoyota

### ISSUE THREAD

**Issue by RockSteadyBeat** [fhempy/fhempy#216]
Hey there folks, 
is there a chance to get Toyota-Connected-Services [https://pypi.org/project/mytoyota/](url) 
running in fhempy??

greetz 
RockSteadyBeat

**Comment by fhempy** [comment]
The implementation looks pretty straight forward. Are you willing to try the implementation on your own? I'm always looking for people who can help me working on fhempy (see [DEVELOPMENT](https://github.com/fhempy/fhempy/blob/master/DEVELOPMENT.md)) 😃

**Comment by RockSteadyBeat** [comment]
Sorry for the late reply, I think I can try to help... But Python isn't my first choice so I'll have to read up on it

**Comment by fhempy** [comment]
Can you please verify if the mytoyota library is still working? I saw that there were many changes yesterday in the repository.
If possible, could you please get in contact with me so that I can do some testing? You can find my e-mail address in this file https://github.com/fhempy/fhempy/blob/master/pyproject.toml
